 // example of custom API
import groovy.json.JsonSlurperClassic 

// used to parse any response JSON
@NonCPS
def jsonParse(def json) {
  new groovy.json.JsonSlurperClassic().parseText(json)
}

// get the username:password from the Jenkins credentials
/**withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: '<CREDENTIAL_ID>',
                    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
   println(env.USERNAME)
   println(env.PASSWORD)
}**/

withCredentials([string(credentialsId: 'slack-webhook', variable: 'SECRET')]) { //set SECRET with the credential content
 println("My secret text is '${SECRET}'")
}

// create http POST request to slack
def resp = httpRequest acceptType: 'APPLICATION_JSON', consoleLogResponseBody: true, contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody: '{"text": "This is a Groovy generated webhook from Jenkinsfile\\nAnd this is another line of text."}', responseHandle: 'NONE', url: 'https://hooks.slack.com/services/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', wrapAsMultipart: false
